# Force dep to vendor non-imported code generators.
required = [
  "github.com/kevinburke/go-bindata",
  "github.com/openshift/library-go/cmd/crd-schema-gen",
]

[prune]
  go-tests = true
  non-go = true
  unused-packages = true

[[prune.project]]
  name = "github.com/kevinburke/go-bindata"
  non-go = false
  unused-packages = false

# openshift
[[override]]
  name = "github.com/openshift/api"
  revision = "515b3561c8a150ecbd1a2dd744c7bd829b3308f2"

[[constraint]]
  name = "github.com/openshift/library-go"
  revision = "dab26bb3a8dc7fccde7227194af755bbff30ce5d"

# kube
[[override]]
  name = "k8s.io/api"
  version = "kubernetes-1.13.4"

[[override]]
  name = "k8s.io/client-go"
  version = "kubernetes-1.13.4"

[[override]]
  name = "k8s.io/apimachinery"
  version = "kubernetes-1.13.4"

[[override]]
  name = "k8s.io/code-generator"
  version = "kubernetes-1.13.4"

# controller-runtime
[[constraint]]
  name = "sigs.k8s.io/controller-runtime"
  revision = "0d6f672f4bf2f096fedb507f6b0bd94da62ae70f"

[[constraint]]
  name = "github.com/aws/aws-sdk-go"
  version = "=v1.15.72"

# codegen
[[constraint]]
  name = "github.com/kevinburke/go-bindata"
  version = "=v3.11.0"

# crd-schema-gen
[[override]]
  name = "sigs.k8s.io/controller-tools"
  revision = "43466124052c1a1aa7d8fd33624b00bc111fb7cf"
  source = "https://github.com/openshift/kubernetes-sigs-controller-tools.git"
[[override]]
  name = "k8s.io/gengo"
  revision = "4242d8e6c5dba56827bb7bcf14ad11cda38f3991"

# For dependency below: Refer to issue https://github.com/golang/dep/issues/1799
[[override]]
name = "gopkg.in/fsnotify.v1"
source = "https://github.com/fsnotify/fsnotify.git"
version="v1.4.7"


[[constraint]]
  name = "github.com/Azure/azure-sdk-for-go"
  version = "27.3.0"
