# This resource is not created by CVO, it is only used as a communication
# mechanism to tell the CVO which ClusterOperator resource to wait for.
# IngressController creates and updates this resource.
apiVersion: config.openshift.io/v1
kind: ClusterOperator
metadata:
  name: ingress
  annotations:
    capability.openshift.io/name: Ingress
    include.release.openshift.io/ibm-cloud-managed: "true"
    include.release.openshift.io/self-managed-high-availability: "true"
    include.release.openshift.io/single-node-developer: "true"
status:
  versions:
    - name: operator
      version: "0.0.1-snapshot"
  relatedObjects:
    - group: ""
      name: openshift-ingress-operator
      resource: namespaces
    - group: ""
      name: openshift-ingress
      resource: namespaces
    - group: ""
      name: openshift-ingress-canary
      resource: namespaces
    - group: operator.openshift.io
      namespace: openshift-ingress-operator
      resource: ingresscontrollers
    - group: ingress.operator.openshift.io
      namespace: openshift-ingress-operator
      resource: dnsrecords
    - group: rbac.authorization.k8s.io
      name: openshift-ingress-operator
      resource: clusterroles
    - group: rbac.authorization.k8s.io
      name: openshift-ingress-operator
      resource: clusterrolebindings
    - group: rbac.authorization.k8s.io
      name: ingress-operator
      namespace: openshift-ingress-operator
      resource: roles
    - group: rbac.authorization.k8s.io
      name: ingress-operator
      namespace: openshift-ingress-operator
      resource: rolebindings
    - group: rbac.authorization.k8s.io
      name: ingress-operator
      namespace: openshift-config
      resource: roles
    - group: rbac.authorization.k8s.io
      name: ingress-operator
      namespace: openshift-config
      resource: rolebindings