apiVersion: apps/v1
kind: Deployment
metadata:
  name: cluster-ingress-operator
  namespace: openshift-cluster-ingress-operator
spec:
  replicas: 1
  selector:
    matchLabels:
      name: cluster-ingress-operator
  template:
    metadata:
      labels:
        name: cluster-ingress-operator
    spec:
      containers:
        - name: cluster-ingress-operator
          image: openshift/cluster-ingress-operator
          ports:
          - containerPort: 60000
            name: metrics
          command:
          - cluster-ingress-operator
          imagePullPolicy: Always
          env:
            - name: WATCH_NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
            - name: OPERATOR_NAME
              value: "cluster-ingress-operator"
      serviceAccountName: cluster-ingress-operator
