# Account for the canary application. 
kind: ServiceAccount
apiVersion: v1
metadata:
  name: ingress-canary
  namespace: openshift-ingress-canary
  annotations:
    capability.openshift.io/name: Ingress
    include.release.openshift.io/ibm-cloud-managed: "true"
    include.release.openshift.io/self-managed-high-availability: "true"
    include.release.openshift.io/single-node-developer: "true"
