# Hello Openshift Ingress Canary service
# Specific values are applied at runtime
kind: Service
apiVersion: v1
metadata: {}
  # metadata values are set at runtime.
spec:
  type: ClusterIP
  ports:
  - name: 8443-tcp
    port: 8443
    protocol: TCP
    targetPort: 8443
  - name: 8888-tcp
    port: 8888
    protocol: TCP
    targetPort: 8888
